// Symbol identifiers for Inversify bindings.
// Add entries here as services/repositories are introduced, e.g.: SomeService: Symbol.for('SomeService'),
export const TYPES = {
	Logger: Symbol.for('Logger'),
	Config: Symbol.for('Config'),
	App: Symbol.for('App'),
	Server: Symbol.for('Server'),
	PostgresHandler: Symbol.for('PostgresHandler'),
	EnvHandler: Symbol.for('EnvHandler'),

	HouseholdRepository: Symbol.for('HouseholdRepository'),
	StudentRepository: Symbol.for('StudentRepository'),
	OperatorRepository: Symbol.for('OperatorRepository'),
	SessionRepository: Symbol.for('SessionRepository'),
	EnrollmentAndCreditRepository: Symbol.for('EnrollmentAndCreditRepository'),
	InvoiceAndPaymentRepository: Symbol.for('InvoiceAndPaymentRepository'),
	UserRepository: Symbol.for('UserRepository'),

	HouseholdsServer: Symbol.for('HouseholdsServer'),
	SessionsServer: Symbol.for('SessionsServer'),
	AttendanceCreditsServer: Symbol.for('AttendanceCreditsServer'),
	BillingServer: Symbol.for('BillingServer'),
	AutopayServer: Symbol.for('AutopayServer'),
	RemindersServer: Symbol.for('RemindersServer'),
	OperatorsServer: Symbol.for('OperatorsServer'),

	AdminController: Symbol.for('AdminController'),
	OperatorController: Symbol.for('OperatorController'),
	HouseholdsController: Symbol.for('HouseholdsController'),
	SessionsController: Symbol.for('SessionsController'),
	AttendanceCreditsController: Symbol.for('AttendanceCreditsController'),
	BillingController: Symbol.for('BillingController'),
	RemindersController: Symbol.for('RemindersController'),
	AutopayController: Symbol.for('AutopayController'),
	ParentController: Symbol.for('ParentController'),
	ParentHouseholdsController: Symbol.for('ParentHouseholdsController'),
	BookingController: Symbol.for('BookingController'),
	ParentAttendanceCreditsController: Symbol.for('ParentAttendanceCreditsController'),
	ParentBillingController: Symbol.for('ParentBillingController'),
	ParentAutopayController: Symbol.for('ParentAutopayController'),
};
