// Symbol identifiers for Inversify bindings.
// Add entries here as services/repositories are introduced, e.g.: SomeService: Symbol.for('SomeService'),
export const TYPES = {
	Logger: Symbol.for('Logger'),
	Config: Symbol.for('Config'),
	App: Symbol.for('App'),
	Server: Symbol.for('Server'),
	PostgresHandler: Symbol.for('PostgresHandler'),
	EnvHandler: Symbol.for('EnvHandler'),

	HouseholdRepository: Symbol.for('HouseholdRepository'),
	StudentRepository: Symbol.for('StudentRepository'),
	OperatorRepository: Symbol.for('OperatorRepository'),
	SessionRepository: Symbol.for('SessionRepository'),
	EnrollmentAndCreditRepository: Symbol.for('EnrollmentAndCreditRepository'),
	InvoiceAndPaymentRepository: Symbol.for('InvoiceAndPaymentRepository'),
	UserRepository: Symbol.for('UserRepository'),
	ClassRepository: Symbol.for('ClassRepository'),

	HouseholdsServer: Symbol.for('HouseholdsServer'),
	SessionsServer: Symbol.for('SessionsServer'),
	AttendanceCreditsServer: Symbol.for('AttendanceCreditsServer'),
	BillingServer: Symbol.for('BillingServer'),
	AutopayServer: Symbol.for('AutopayServer'),
	RemindersServer: Symbol.for('RemindersServer'),
	OperatorsServer: Symbol.for('OperatorsServer'),
	ClassesServer: Symbol.for('ClassesServer'),
	AvatarsServer: Symbol.for('AvatarsServer'),
	AvatarStorage: Symbol.for('AvatarStorage'),

	AdminController: Symbol.for('AdminController'),
	AdminOperatorsController: Symbol.for('AdminOperatorsController'),
	AdminHouseholdsController: Symbol.for('AdminHouseholdsController'),
	OperatorController: Symbol.for('OperatorController'),
	HouseholdsController: Symbol.for('HouseholdsController'),
	SessionsController: Symbol.for('SessionsController'),
	AttendanceCreditsController: Symbol.for('AttendanceCreditsController'),
	BillingController: Symbol.for('BillingController'),
	RemindersController: Symbol.for('RemindersController'),
	AutopayController: Symbol.for('AutopayController'),
	ClassesController: Symbol.for('ClassesController'),
	HouseholdController: Symbol.for('HouseholdController'),
	HouseholdHouseholdsController: Symbol.for('HouseholdHouseholdsController'),
	BookingController: Symbol.for('BookingController'),
	HouseholdAttendanceCreditsController: Symbol.for('HouseholdAttendanceCreditsController'),
	HouseholdBillingController: Symbol.for('HouseholdBillingController'),
	HouseholdAutopayController: Symbol.for('HouseholdAutopayController'),
	HouseholdSettingsController: Symbol.for('HouseholdSettingsController'),
	OperatorSettingsController: Symbol.for('OperatorSettingsController'),
};
